# Generated by Django 3.2.8 on 2021-10-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOO', 'Buch'), ('MAG', 'Zeitschrift'), ('CDA', 'Audio-CD'), ('CDR', 'CD-ROM'), ('CAS', 'Kassette'), ('DVD', 'DVD'), ('GAM', 'Spiel'), ('ZZZ', 'anderes Medium')], default='BOO', max_length=3)),
                ('title_text', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, upload_to='covers/')),
                ('isbn_ean_text', models.CharField(blank=True, max_length=13)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='media.author')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.series')),
            ],
        ),
    ]
