# Generated by Django 3.2.8 on 2021-10-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_medium_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medium',
            name='authors',
        ),
        migrations.AddField(
            model_name='medium',
            name='authors',
            field=models.ManyToManyField(to='media.Author'),
        ),
    ]
