# Generated by Django 3.2.8 on 2021-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20211021_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='authors',
            field=models.ManyToManyField(db_index=True, to='media.Author'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='title_text',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Titel'),
        ),
    ]
