# Generated by Django 3.2.8 on 2021-10-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20211021_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='authors',
            field=models.ManyToManyField(db_index=True, to='media.Author', verbose_name='Autor(en)'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers/', verbose_name='Titelbild'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='isbn_ean_text',
            field=models.CharField(blank=True, max_length=13, verbose_name='ISBN/EAN'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.series', verbose_name='gehört zur Reihe'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='type',
            field=models.CharField(choices=[('BOO', 'Buch'), ('MAG', 'Zeitschrift'), ('CDA', 'Audio-CD'), ('CDR', 'CD-ROM'), ('CAS', 'Kassette'), ('DVD', 'DVD'), ('GAM', 'Spiel'), ('ZZZ', 'anderes Medium')], default='BOO', max_length=3, verbose_name='Medienart'),
        ),
    ]
