# Generated by Django 3.2.8 on 2021-10-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20211021_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='components_num',
            field=models.PositiveSmallIntegerField(default=1, help_text='Besteht das Medium aus mehreren Stücken? z.B. Buch mit 2 CDs = 3', verbose_name='Anzahl Bestandteile'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='title_text',
            field=models.CharField(db_index=True, help_text='ggf. Reihe nicht wiederholen', max_length=200, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='medium',
            name='type',
            field=models.CharField(choices=[('BOO', 'Buch'), ('MAG', 'Zeitschrift'), ('CDA', 'Audio-CD'), ('CDR', 'CD-ROM'), ('CAS', 'Kassette'), ('DVD', 'DVD'), ('GAM', 'Spiel'), ('MUL', 'mehrere Medien'), ('ZZZ', 'anderes Medium')], default='BOO', max_length=3, verbose_name='Medienart'),
        ),
    ]
