# Generated by Django 3.2.8 on 2021-10-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_medium_series_index_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autoren'},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name': 'Medium', 'verbose_name_plural': 'Medien'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Reihe', 'verbose_name_plural': 'Reihen'},
        ),
        migrations.AddField(
            model_name='medium',
            name='barcode_version_num',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Barcode vorhanden'),
        ),
    ]
