# Generated by Django 3.2.8 on 2021-10-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.user'),
        ),
    ]
