# Generated by Django 3.2.8 on 2021-10-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_group_group_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Klasse', 'verbose_name_plural': 'Klassen'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Nutzer', 'verbose_name_plural': 'Nutzer'},
        ),
    ]
